SFC/Controllers/ChefController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using System.Data.Entity;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SFC.Models;

namespace SFC.Controllers
{
    public class ChefController : Controller
    {
        // GET: Chef
        public List<Food> getListFoods()
        {
            List<Food> list = new List<Food>();
            list = DatabaseService.DBGetList<Food>("Menu");
            return list;
        }
        public List<Order> getListOrder()
        {
            List<Order> list = new List<Order>();
            list = DatabaseService.DBGetList<Order>("Order");
            return list;
        }
        public async Task<Order> getOrderWithNameFood(int id)
        {
            Order order = await DatabaseService.DBGetRecord<Order>("Order/" + id.ToString());
            List<Food> listFood = DatabaseService.DBGetList<Food>("Menu");
            List<string> key = new List<string>(order.items.Keys);
            for (int i = 0; i < key.Count(); i++)
            {
                for (int j = 0; j < listFood.Count(); j++)
                {
                    if (listFood[j] != null)
                    {
                        if (listFood[j].id == int.Parse(key[i].Replace("\"", "")))
                        {
                            order.foods.Add(new Food() { id = listFood[j].id, name = listFood[j].name, quantity = order.items[key[i]] });
                        }
                    }
                    else { continue; }
                }
            }
            return order;
        }
        public ActionResult Index()
        {
            List<Order> list = getListOrder();
            List<Food> listFood = getListFoods();
            List<Order> orders = new List<Order>();
            for (int i = 0; i < list.Count(); i++)
            {
                List<string> key = new List<string>(list[i].items.Keys);
                for (int j = 0; j < key.Count(); j++)
                {
                    for (int k = 0; k < listFood.Count(); k++)
                    {
                        if (listFood[k] != null)
                        {
                            if (listFood[k].id == int.Parse(key[j].Replace("\"", "")))
                            {
                                list[i].foods.Add(new Food() { id = listFood[k].id, name = listFood[k].name, quantity = list[i].items[key[j]] });
                            }
                        }
                        else { continue; }
                    }
                }
            }
            for (int i = 0; i < list.Count(); i++)
            {
                if (list[i].numberOfCompleted == 0)
                {
                    orders.Add(new Order() { id = list[i].id, numberOfCompleted = list[i].numberOfCompleted, username = list[i].username, foods = list[i].foods, items = list[i].items });
                }
            }

            return View(orders);
        }
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            Order order = await getOrderWithNameFood(id);
            return View(order);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Order order)
        {
            Order order1 = await DatabaseService.DBGetRecord<Order>("Order/" + order.id.ToString());
            order1.numberOfCompleted = order1.items.Count();
            await DatabaseService.DBUpdate<Order>(order1, "Order/" + order.id.ToString());
            return RedirectToAction("Index");
        }

        public ActionResult Complete()
        {
            List<Order> list = getListOrder();
            List<Food> listFood = getListFoods();
            List<Order> orders = new List<Order>();
            for (int i = 0; i < list.Count(); i++)
            {
                List<string> key = new List<string>(list[i].items.Keys);
                for (int j = 0; j < key.Count(); j++)
                {
                    for (int k = 0; k < listFood.Count(); k++)
                    {
                        if (listFood[k] != null)
                        {
                            if (listFood[k].id == int.Parse(key[j].Replace("\"", "")))
                            {
                                list[i].foods.Add(new Food() { id = listFood[k].id, name = listFood[k].name, quantity = list[i].items[key[j]] });
                            }
                        }
                        else { continue; }
                    }
                }
            }
            for (int i = 0; i < list.Count(); i++)
            {
                if (list[i].numberOfCompleted != 0)
                {
                    orders.Add(new Order() { id = list[i].id, numberOfCompleted = list[i].numberOfCompleted, username = list[i].username, foods = list[i].foods, items = list[i].items });
                }
            }

            return View(orders);
        }

        public async Task<ActionResult> sendNotification(String name, int id)
        {
            CustomerAccount acc = await DatabaseService.DBGetRecord<CustomerAccount>("Account/Customer/" + name);
            Order order = await getOrderWithNameFood(id);
            var senderEmail = new MailAddress(ManagerAccountService.current.email, ManagerAccountService.current.name);
            var receiverEmail = new MailAddress(acc.email);
            var password = "vendor123";
            var sub = "Notice of completed order";
            var body = "Dear ";
            body = body + acc.name + ",\n\nYour order includes:\n";

            for (int i = 0; i < order.foods.Count; i++)
            {
                body = body + order.foods[i].name + "  x" + order.foods[i].quantity.ToString() + "\n";
            }
            body = body + "\ncompleted, please go to " + ManagerAccountService.current.name + " to receive food\n" +
                          "\nThank you and see you again !";
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(senderEmail.Address, password)
            };
            using (var mess = new MailMessage(senderEmail, receiverEmail)
            {
                Subject = sub,
                Body = body
            })
            {
                smtp.Send(mess);
            }
            return RedirectToAction("Complete");
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public JsonResult CheckValidUser(string username, string password)
        {
            string result = "Success";
            ManagerAccount cur = new ManagerAccount();
            try
            {
                cur = ManagerAccountService.CheckLogin(username, password);
            }
            catch (Exception e)
            {
                if (e.Message != null)
                    result = e.Message;
            }
            ViewBag.currentAccount = cur;
            Session["vendorID"] = cur.id;
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

SFC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SFC.Models;

namespace SFC.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            if (AccountService.current.username == "Login")
                return View();
            return RedirectToAction("Account");
        }

        public ActionResult Account()
        {
            return View(AccountService.current);
        }

        public ActionResult Signup()
        {
            return View();
        }

        public ActionResult Manager()
        {
            return View();
        }

        public ActionResult Chef()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CheckValidUser(string username, string password)
        {
            string result = "Success";
            CustomerAccount cur = new CustomerAccount();
            try
            {
                cur = AccountService.CheckLogin(username, password);
            }
            catch (Exception e)
            {
                if (e.Message != null)
                    result = e.Message;
            }
            ViewBag.currentAccount = cur;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<JsonResult> SignUp(string username, string password, string name, string birthYear, string email)
        {
            string result = "Success";
            try
            {
                bool check = await AccountService.CheckSignUp(username, password, name, birthYear, email);
            }
            catch (Exception e)
            {
                if (e.Message != null)
                    result = e.Message;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

SFC/Views/Chef/Complete.cshtml
@model IEnumerable<SFC.Models.Order>
@{
    ViewBag.Title = "Complete";
    Layout = "~/Views/Shared/_LayoutChef.cshtml";
}

<section class="mbr-section content5 cid-s2h0Bx5c2F" id="content5-1h">
    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">Completed Order</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">
                    List of completed orders, chef can send notifications to customers
                </h3>
            </div>
        </div>
    </div>
</section>
<section class="mbr-section content8 cid-s2h0HOricl" id="content8-1j">
    <div class="container">
        <div class="media-container-row title">
            <div class="col-12 col-md-8">
                <div class="mbr-section-btn align-center">
                    <a class="btn btn-black-outline display-4" @Html.ActionLink("List Orders", "Index", "Chef")></a>
                    <a class="btn btn-primary display-4" @Html.ActionLink("Completed Order", "Complete", "Chef")></a>
                </div>
            </div>
        </div>
    </div>
</section>
@foreach (var item in Model)
{
    <section class="mbr-section info1 cid-s4qj9HvLC4" id="info1-28">
        <div class="container">
            <div class="row justify-content-center content-row">
                <div class="media-container-column title col-12 col-lg-7 col-md-6">
                    <h3 class="mbr-section-subtitle align-left mbr-light pb-3 mbr-fonts-style display-2">
                        <strong># @Html.DisplayFor(Model => item.id)</strong>
                    </h3>
                    <h2 class="align-left mbr-bold mbr-fonts-style display-5">
                        Customer: <span style="font-weight: normal;">@Html.DisplayFor(Model => item.username)</span><br />Food:<br />
                        <table>
                            @for (int i = 0; i < item.foods.Count(); i++)
                            {
                                if (item.foods[i].quantity != 0)
                                {
                                    <tr>
                                        <th style="font-weight: normal;">&emsp; &emsp; &ensp; @Html.DisplayFor(Model => item.foods[i].name)</th>
                                        <th style="font-weight: normal;">&nbsp; x @Html.DisplayFor(Model => item.foods[i].quantity)</th>
                                    </tr>
                                }
                            }
                        </table>
                </div>
                <div class="media-container-column col-12 col-lg-3 col-md-4">
                    <div class="mbr-section-btn align-right py-4">
                        <a class="btn btn-primary display-4"
                           data-toggle="modal"
                           data-target="#exampleModal"
                           onclick="location.href='@Url.Action("sendNotification", "Chef", new { name = item.username, id = item.id })'"
                          >
                            Send notification
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
}
<!-- Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sending...</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 100%"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>


SFC/Views/Chef/Edit.cshtml
@model SFC.Models.Order

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutChef.cshtml";
}

<section class="mbr-section content5 cid-s2h0Bx5c2F" id="content5-1h">
    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">Order infomation</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">
                    Chef checks the order information before marking the completion
                </h3>
            </div>
        </div>
    </div>
</section>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div style="padding-left: 400px; padding-right: 400px">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="font-size:25px">
            <b> Order ID: </b> @Html.DisplayFor(Model => Model.id)
            <div class="col-md-10" style="display:none">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>  
        </div>

        <div class="form-group" style="font-size:25px">
            <b>Customer's username:</b> @Html.DisplayFor(Model => Model.username)
        </div>

        <div class="form-group" style="font-size:25px">
            <b>Time order:</b> @Html.DisplayFor(Model => Model.time)
        </div>

        <div class="form-group" style="font-size:25px">
            <b>Number of completed food:</b> @Html.DisplayFor(Model => Model.numberOfCompleted)
        </div>

        <div class="form-group" style="font-size:25px">
            <b>Foods ordered: </b>
            <div class="col-md-10" style="padding-left: 90px">
                <table>
                    <tr><th style="font-weight:normal; text-align:center">Food Name &emsp; &emsp;</th><th style="font-weight:normal; text-align:center">Quantity</th></tr>
                    @for (int i = 0; i < Model.foods.Count(); i++)
                    {
                        if (Model.foods[i].quantity != 0)
                        {
                            <tr>
                                <th style="font-weight:normal; text-align:left">
                                    @Html.DisplayFor(Model => Model.foods[i].name)
                                </th>
                                <th style="font-weight:normal; text-align:center">
                                    @Html.DisplayFor(Model => Model.foods[i].quantity)
                                </th>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>

        <div class="form-group" style="font-size:25px">
            <b>Request:</b> @Html.DisplayFor(Model => Model.request)
        </div>
        <div class="form-group" style="text-align:center">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Complete" class="btn btn-success"/>
            </div>
        </div>
        <hr />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SFC/Views/Chef/Index.cshtml
@model IEnumerable<SFC.Models.Order>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutChef.cshtml";
}

<section class="mbr-section content5 cid-s2h0Bx5c2F" id="content5-1h">
    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">List orders</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">
                    List of orders to be processed
                </h3>


            </div>
        </div>
    </div>
</section>

<section class="mbr-section content8 cid-s2h0HOricl" id="content8-1j">
    <div class="container">
        <div class="media-container-row title">
            <div class="col-12 col-md-8">
                <div class="mbr-section-btn align-center">
                    <a class="btn btn-primary display-4" @Html.ActionLink("List Orders", "Index", "Chef")></a>
                    <a class="btn btn-black-outline display-4" @Html.ActionLink("Completed Order", "Complete", "Chef")></a>
                </div>
            </div>
        </div>
    </div>
</section>

@foreach (var item in Model)
{
    if (item != null)
    {
        <section class="mbr-section info1 cid-s4qj9HvLC4" id="info1-28">
            <div class="container">
                <div class="row justify-content-center content-row">
                    <div class="media-container-column title col-12 col-lg-7 col-md-6">
                        <h3 class="mbr-section-subtitle align-left mbr-light pb-3 mbr-fonts-style display-2">
                            <strong># @Html.DisplayFor(Model => item.id)</strong>
                        </h3>
                        <h2 class="align-left mbr-bold mbr-fonts-style display-5">
                            Customer: <span style="font-weight: normal;">@Html.DisplayFor(Model => item.username)</span><br />Food:<br />
                            <table>
                                @for (int i = 0; i < item.foods.Count(); i++)
                                {
                                    if (item.foods[i].quantity != 0)
                                    {
                                        <tr>
                                            <th style="font-weight: normal;">&emsp; &emsp; &ensp; @Html.DisplayFor(Model => item.foods[i].name)</th>
                                            <th style="font-weight: normal;">&nbsp; x @Html.DisplayFor(Model => item.foods[i].quantity)</th>
                                        </tr>
                                    }
                                }
                            </table>
                    </div>
                    <div class="media-container-column col-12 col-lg-3 col-md-4">
                        <div class="mbr-section-btn align-right py-4">
                            <a class="btn btn-primary display-4"
                               data-toggle="modal"
                               data-target="#exampleModal"
                               onclick="location.href='@Url.Action("Edit", "Chef", new { id = item.id, food = item.foods })'">
                                Complete
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    }
    else { continue; }
}

SFC/Views/Chef/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/M_Content/loginstyle.css">

<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/M_Scripts/dataTable/scripts.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="~/M_Scripts/dataTable/datatables-demo.js"></script>

<script>
    // Check key "Enter" in textbox password
    function runScript(e) {
        if (e.keyCode == 13) {
            login();
            return false;
        }
    }
   function login ()
   {
       var inputUser = document.getElementById("username").value
       var inputPass = document.getElementById("password").value
        $.ajax({
            type: "post",
            url: "@Url.Action("CheckValidUser")",
            data: {
                'username': inputUser,
                'password': inputPass,
            },
            success: function (result) {
                if (result != "Success") {
                    document.getElementById("msg").innerHTML = '\xa0\xa0\xa0\xa0\xa0\xa0\xa0' + result + '\xa0\xa0\xa0\xa0\xa0\xa0\xa0';
                    document.getElementById("msg").style.visibility = 'visible';
                }
                else {
                    window.location.href = "@Url.Action("Index","Chef")";
                    document.getElementById("msg").style.visibility = 'hidden';
                }
            }
        })
    }
</script>
<section class="mbr-section content5 cid-s2gPyz5iF6" id="content5-x">

    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">Login as chef</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">Please login your account</h3>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section form1 cid-s2gT73reu9" id="form1-12">

    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-12 col-lg-8">
            </div>
        </div>
    </div>
</section>
<!---Formbuilder Form--->
<div id="login">
    <h3 class="text-center text-info pt-5">Login form</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-7" style="background-color:white">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" action="" method="post" style="background-color:#65b6cc">
                        <br />
                        <h3 class="text-center text-white">Login</h3>

                        <div class="form-group">
                            <label for="username" class="text-white">Username:</label><br>
                            <input type="text" name="username" id="username" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="password" class="text-white">Password:</label><br>
                            <input type="password" name="password" id="password" onkeypress="return runScript(event)" class="form-control">
                        </div>

                        <div class="justify-content-sm-center text-center">
                            <input type="button" name="submit" class="btn btn-primary btn-md" onclick=login() style="background-color:#016485" value="Submit">
                        </div>

                        <div class=" text-center ">
                            <label for="msg" id="msg" style=" border:1px solid #550519; background-color:#b20202; visibility:hidden;" class="text-primary text-white"> abc </label><br>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="features1 cid-s2gQKxSTuL" id="features1-11">

    <div class="container">
        <div class="media-container-row">
        </div>
    </div>

</section>

SFC/Views/Chef/sendNotification.cshtml
@{
    ViewBag.Title = "sendNotification";
    Layout = "~/Views/Shared/_LayoutChef.cshtml";
}

<h2>sendNotification</h2>