SFC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SFC.Models;

namespace SFC.Controllers
{
    public class HomeController : Controller
    {
        Order order;

        [HttpGet]
        public ActionResult Index()
        {
            if (TempData["Order"] == null)
            {
                order = new Order();
                TempData.Add("Order", order);
                ViewData.Add("Order", order);
               
            }
            else
            {
                order = (Order)TempData["Order"];
                TempData.Keep();
            }

            Menu foodList = Menu.getMenu();
            
            return View(foodList);
        }

        public ActionResult AboutUs()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        /* ----------------------------------- METHODS FOR CART---------------------*/
        public ActionResult Cart()
        {

            if (TempData["Order"] == null)
            {
                order = new Order();
                TempData["Order"] = order;
            }
            else
            {
                order = (Order)TempData["Order"];
                TempData.Keep();
            }
            return View(order);
        }

        [HttpPost]
        public bool AddItemToCart(int id, int quantity)
        {
            order = (Order)TempData["Order"];
            TempData.Keep();
            return order.addItemToCart(id, quantity);
        }

        [HttpPost]
        public JsonResult ChangeQuantity(int id, int quantity)
        {
            //
            order = (Order)TempData["Order"];
            TempData.Keep();

            order.changeQuantity(id, quantity); 
            return Json(new { totalCost = order.getTotalCost() });
        }

        public JsonResult RemoveItem(int id)
        {
            //
            order = (Order)TempData["Order"];
            TempData.Keep();

            order.removeCartItem(id);
            return Json(new { totalCost = order.getTotalCost() });
        }
    }
}

SFC/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SFC.Models;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.IO;
using System.Web.Helpers;
using System.Threading;
using Org.BouncyCastle.Asn1.Nist;
using FireSharp.Extensions;
using System.Web.Script.Serialization;
using Microsoft.Ajax.Utilities;
using RestSharp;
using Org.BouncyCastle.Ocsp;
using System.Threading.Tasks;
using ZaloPay.Helper;
using ZaloPay.Helper.Crypto;
using Newtonsoft.Json;

namespace SFC.Controllers
{
    public class PaymentController : Controller
    {
        Order order;
        Wallet wallet;

        public ActionResult Index()
        {
            if (TempData["Order"] == null)
            {
                order = new Order();
                order.id = OrderList.orders.Count();
                TempData["Order"] = order;
            }
            else
            {
                order = (Order)TempData["Order"];
                TempData.Keep();
            }
            return View(order);
        }

        public ActionResult HandleResultPayment(string partnerCode, string accessKey, string requestID, string amount, string orderID, string orderInfo, string orderType, string transID, int errorCode, string mesage, string localMessage, string payType, string responseTime, string extraData, string signature)
        {
            if (errorCode == 0)
            {
                int id = Int32.Parse(orderInfo);
                if (!OrderList.orders.ContainsKey(id))
                {
                    OrderList.orders.Add(id, null);
                }
                TempData["success"] = true;
            }
            else TempData["success"] = false;
            return View();
        }
        
        [HttpPost]
        public JsonResult RequestPayment(string nameWallet)
        {
            order = (Order)TempData["Order"];
            TempData.Keep();
            if (nameWallet == "Momo")
            {
                wallet = new MomoWallet(order.totalCost, order.id.ToString());
            }
            else
            {
                wallet = new ZaloPayWallet(order.totalCost, order.id.ToString());
            }
            wallet.sendPaymentRequest();
            return Json(new { responseUrl = wallet.getPayUrl(), qrCode = wallet.getQRUrl() });
        }

        async System.Threading.Tasks.Task notifyPaymentObservers()
        {
            _ = order.makeOrder();
            try
            {
                await DatabaseService.DBWrite<Order>(order, "Order/" + order.id.ToString());
            }
            catch (Exception e)
            {
                Console.WriteLine("Execute fail: " + e.Message.ToString());
            }
            
        }

        [HttpPost]
        public void confirmOrder(string request)
        {
            order = (Order) TempData["Order"];
            TempData.Keep();
            order.request = request;
            TempData["confirmed"] = true;
        }

        [HttpPost]
        public JsonResult CheckPaid()
        {
            order = (Order)TempData["Order"];
            bool paid = false;
            if (order != null && OrderList.orders.ContainsKey(order.id))
            {
                order.paid = paid = true;
                OrderList.orders[order.id] = order;
                order.username = AccountService.current.username;
                TempData.Remove("Order");
                _ = notifyPaymentObservers();
            }
            TempData.Keep();
            
            return Json(new { isPaid = paid});
        }

        
        [HttpPost]
        public void HandleIPN()
        {
            Wallet wallet = new MomoWallet(0, "0");
            using (Stream IPNReceive = Request.InputStream)
            {
                wallet.handleIPN(IPNReceive);
                JObject jmessage = JObject.Parse(wallet.getJsonIPN());

                if (jmessage.GetValue("errorCode").ToString() == "0")
                {
                    int id = Int32.Parse(jmessage.GetValue("orderInfo").ToString());             
                    OrderList.orders.Add(id, null);
                }                
            }
            
        }

        [HttpPost]
        public void ZaloCallBack()
        {
            Wallet wallet = new ZaloPayWallet(0, "0");
            using (Stream IPNReceive = Request.InputStream)
            {
                wallet.handleIPN(IPNReceive);
                JObject jmessage = JObject.Parse(wallet.getJsonIPN());
                
                var ipnJson = JsonConvert.DeserializeObject<Dictionary<string, object>>(wallet.getJsonIPN());


                var data = JsonConvert.DeserializeObject<Dictionary<string, object>>(ipnJson["data"].ToString());
                var orderId = Int32.Parse(data["item"].ToString());
                OrderList.orders.Add(orderId, null);
            }

        }


    }
    
    interface Wallet
    {
        void sendPaymentRequest();
        string getJsonResponse();
        void handleIPN(Stream IPNReceiver);
        string getJsonIPN();
        string getPayUrl();
        string getQRUrl();
    }

    public class MomoWallet : Wallet
    {
        long totalCost;
        string orderInfo;
        string jsonResponse;
        string jsonIPN;
        string payUrl;
        string qrUrl;

        public MomoWallet(long totalCost, string orderInfo)
        {
            this.totalCost = totalCost;
            this.orderInfo = orderInfo;

        }

        // Http Request to Momo Server
        public void sendPaymentRequest()
        {
            string endpoint = "https://test-payment.momo.vn/gw_payment/transactionProcessor";
            string orderid = Guid.NewGuid().ToString();
            string requestId = Guid.NewGuid().ToString();
            string partnerCode = "MOMO";
            string accessKey = "F8BBA842ECF85";
            string amount = totalCost.ToString();
            string orderInfo = this.orderInfo;
            string returnUrl = "http://a0fddb494d35.ngrok.io/Payment/HandleResultPayment/";
            string notifyUrl = "http://a0fddb494d35.ngrok.io/Payment/HandleIPN";
            string secretKey = "K951B6PE1waDMi640xX08PD3vg6EkVlz";
            string extraData = "email=uyenhuynh@gmail.com";

            string rawHash = "partnerCode=" +
                partnerCode + "&accessKey=" +
                accessKey + "&requestId=" +
                requestId + "&amount=" +
                amount + "&orderId=" +
                orderid + "&orderInfo=" +
                orderInfo + "&returnUrl=" +
                returnUrl + "&notifyUrl=" +
                notifyUrl + "&extraData=" +
                extraData;

            byte[] keyByte = Encoding.UTF8.GetBytes(secretKey);
            byte[] messsageBytes = Encoding.UTF8.GetBytes(rawHash);
            var hmacsha256 = new HMACSHA256(keyByte);
            byte[] hashmessage = hmacsha256.ComputeHash(messsageBytes);
            string hex = BitConverter.ToString(hashmessage);
            string signature = hex.Replace("-", "").ToLower();

            JObject message = new JObject
            {
                { "partnerCode", partnerCode },
                { "accessKey", accessKey },
                { "requestId", requestId },
                { "amount", amount },
                { "orderId", orderid },
                { "orderInfo", orderInfo },
                { "returnUrl", returnUrl },
                { "notifyUrl", notifyUrl },
                { "extraData", extraData },
                { "requestType", "captureMoMoWallet" },
                { "signature", signature }
            };

            try
            {
                HttpWebRequest httpWReq = (HttpWebRequest)WebRequest.Create(endpoint);

                var postData = message.ToString();

                var data = Encoding.UTF8.GetBytes(postData);

                httpWReq.ProtocolVersion = HttpVersion.Version11;
                httpWReq.Method = "POST";
                httpWReq.ContentType = "application/json";

                httpWReq.ContentLength = data.Length;
                httpWReq.ReadWriteTimeout = 30000;
                httpWReq.Timeout = 15000;
                Stream stream = httpWReq.GetRequestStream();
                stream.Write(data, 0, data.Length);
                stream.Close();

                HttpWebResponse response = (HttpWebResponse)httpWReq.GetResponse();

                using (var reader = new StreamReader(response.GetResponseStream()))
                {

                    string temp = null;
                    while ((temp = reader.ReadLine()) != null)
                    {
                        jsonResponse += temp;
                    }
                    JObject jmessage = JObject.Parse(jsonResponse);
                    payUrl = jmessage.GetValue("payUrl").ToString();
                    qrUrl = jmessage.GetValue("qrCodeUrl").ToString();                 
                }
            }
            catch (WebException e)
            {
                // 
            }


        }

        public string getJsonResponse()
        {
            return jsonResponse;
        }

        // Receive IPN from Momo Server
        public void handleIPN(Stream IPNReceive)
        {
            using (StreamReader reader = new StreamReader(IPNReceive, Encoding.ASCII))
            {
                string temp = null;
                while ((temp = reader.ReadLine()) != null)
                {
                    jsonIPN += temp;
                }
            }
            var dict = HttpUtility.ParseQueryString(jsonIPN);
            jsonIPN = new JavaScriptSerializer().Serialize(
                                dict.AllKeys.ToDictionary(k => k, k => dict[k])
                       );
        }

        public string getJsonIPN()
        {
            return jsonIPN;
        }

        public string getPayUrl()

SFC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About us";
}
<section class="engine"><a href="https://mobirise.info/p">site templates free download</a></section>
<section class="mbr-section content5 cid-s2gYFsi540" id="content5-1c">





    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">About Us</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">We are trying hard to introduce Smart Food Court System</h3>


            </div>
        </div>
    </div>
</section>

<section class="testimonials1 cid-s2gYITriqs" id="testimonials1-1e">




    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 align-center">
                <h2 class="pb-3 mbr-fonts-style display-2">
                    WE ARE 3NUT GROUP
                </h2>
                <h3 class="mbr-section-subtitle mbr-light pb-3 mbr-fonts-style display-5">
                    Faculity of Computer Science and Engineering&nbsp;
                </h3>
            </div>
        </div>
    </div>

    <div class="container pt-3 mt-2">
        <div class="media-container-row">
            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">Vo Hoang Hai Nam</p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>

            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Huynh Thi Uyen
                        </p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>

            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Dang Ngoc Tam
                        </p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>

            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">Nguyen Hoang Nhat</p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>

            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Tran Trong Nghia
                        </p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>


        </div>
    </div>
</section>

<section class="mbr-section article content1 cid-s2h0adhtbQ" id="content2-1f">



    <div class="container">
        <div class="media-container-row">
            <div class="mbr-text col-12 col-md-8 mbr-fonts-style display-4">
                <blockquote><p><strong>About our project</strong></p><p><strong>We use .......</strong></p></blockquote>
            </div>
        </div>
    </div>
</section>

SFC/Views/Home/AboutUs.cshtml
@{
    ViewBag.Title = "About us";
}
<section class="engine"><a href="https://mobirise.info/p">site templates free download</a></section>
<section class="mbr-section content5 cid-s2gYFsi540" id="content5-1c">





    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">About Us</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">We are trying hard to introduce Smart Food Court System</h3>


            </div>
        </div>
    </div>
</section>

<section class="testimonials1 cid-s2gYITriqs" id="testimonials1-1e">




    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 align-center">
                <h2 class="pb-3 mbr-fonts-style display-2">
                    WE ARE 3NUT GROUP
                </h2>
                <h3 class="mbr-section-subtitle mbr-light pb-3 mbr-fonts-style display-5">
                    Faculity of Computer Science and Engineering&nbsp;
                </h3>
            </div>
        </div>
    </div>

    <div class="container pt-3 mt-2">
        <div class="media-container-row">
            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">Vo Hoang Hai Nam</p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>

            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Huynh Thi Uyen
                        </p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>

            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Dang Ngoc Tam
                        </p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>

            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">Nguyen Hoang Nhat</p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>

            <div class="mbr-testimonial p-3 align-center col-12 col-md-6 col-lg-4">
                <div class="panel-item p-3">
                    <div class="card-block">
                        <div class="testimonial-photo">
                            <img src="~/assets/images/hcmut-122x117.png" alt="" title="">
                        </div>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Tran Trong Nghia
                        </p>
                    </div>
                    <div class="card-footer">


                    </div>
                </div>
            </div>


        </div>
    </div>
</section>

<section class="mbr-section article content1 cid-s2h0adhtbQ" id="content2-1f">



    <div class="container">
        <div class="media-container-row">
            <div class="mbr-text col-12 col-md-8 mbr-fonts-style display-4">
                <blockquote>
                    <p>
                    <strong>About our project</strong></p>
                    <p>
                            We use ASP.NET to build this website. This is the first software project of all team members.
                            Despite the difficulties of learning the new platform, after 3 weeks we had a demo with the basic features completed.
                            Hope you will love our website and efforts <3 Love you 3000.
                     </p>
                </blockquote>
            </div>
        </div>
    </div>
</section>

SFC/Views/Home/Cart.cshtml
@using SFC.Models
@model Order
@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/assets/socicon/css/payStyles.css">
<script src="~/assets/myJS/myJS.js" async></script>
<script>
    if (document.readyState == 'loading') {
        document.addEventListener('DOMContentLoaded', ready)
    } else {
        ready()
    }
    function ready() {
        var removeCartItemButtons = document.getElementsByClassName('btn-danger')
        for (var i = 0; i < removeCartItemButtons.length; i++) {
            var button = removeCartItemButtons[i]
            button.addEventListener('click', removeCartItem)
        }

        var quantityInputs = document.getElementsByClassName('cart-quantity-input')
        for (var i = 0; i < quantityInputs.length; i++) {
            var input = quantityInputs[i]
            input.addEventListener('change', quantityChanged)
        }

        var btnPurchase = document.getElementsByName('btn-purchase')[0]
        btnPurchase.addEventListener('click', purchaseClicked)
    }

    function purchaseClicked(event) {
        var btn = event.target
        var btnPrice = document.getElementsByClassName('cart-total-price')[0]
        var price = parseInt(btnPrice.innerText.replace('$', ''))
        if (price == '0') {
            alert('No no no, choose our food first babe <3')
        }
        else {
            window.location.href='@Url.Action("Index", "Payment")'
        }
    }

    function removeCartItem(event) {
        var buttonClicked = event.target
        var id = buttonClicked.parentElement.children[0].innerText
        buttonClicked.parentElement.parentElement.remove()

        $.ajax({
            type: 'post',
            url: "@Url.Action("RemoveItem")",
            data: {
                'id': id,
            },
             success: function (result) {
                JSON.stringify(result)
                document.getElementsByClassName('cart-total-price')[0].innerText = '$' + result['totalCost']
             }
        })
    }

    function quantityChanged(event) {
        var input = event.target
        var group = input.parentElement
        var id = group.children[0].innerText
        var quantity = group.children[1].value

        $.ajax({
            type: 'post',
            url: "@Url.Action("ChangeQuantity")",
            data: {
                'id': id,
                'quantity': quantity,
            },
            dataType: 'json',
            success: function (result) {
                JSON.stringify(result)
                document.getElementsByClassName('cart-total-price')[0].innerText = '$' + result['totalCost']
            }
        })
    }

</script>

<section class="mbr-section content5 cid-s2gNlDMF3j" id="content5-r">
    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">MY CART</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">Please check your order carefully</h3>


            </div>
        </div>
    </div>
</section>

<section class="container container-fluid"style="background-color: #17a2b80f;">
    <div class="row" style="display: flex;">
        <div class=" col-4 border-bottom border-dark cart-header cart-column ">ITEM </div>
        <div class=" col-2 border-bottom border-dark cart-price cart-header cart-column ">PRICE </div>
        <div class=" col-lg-5 col-md-4 border-bottom border-dark cart-quantity cart-header cart-column ">QUANTITY</div>

    </div>
    @*
        <div class="cart-row">
            <span class="cart-item cart-header cart-column">ITEM</span>
            <span class="cart-price cart-header cart-column">PRICE</span>
            <span class="cart-quantity cart-header cart-column">QUANTITY</span>
        </div>*@
    @*@{
            if (@Model.totalCost != 0)
            {
                foreach (var item in Model.items)
                {
                    var dbItem = Model.getItem(item.Key);
                    <div class="cart-row">
                        <div class="cart-item cart-column">
                            <img class="cart-item-image" src="@dbItem.imageSrc" height="100">
                            <span class="cart-item-title">@dbItem.name</span>
                            <p hidden>@item.Key</p>
                        </div>
                        <span class="cart-price cart-column">$@dbItem.price.ToString()</span>
                        <div class="cart-quantity cart-column">
                            <p hidden> @item.Key </p>
                            <input class="cart-quantity-input" type="number" value="@item.Value" min="0">
                            <button class="btn btn-danger" type="button">REMOVE</button>
                        </div>
                    </div>
                }
            }
        }*@
    @{
        if (@Model.totalCost != 0)
        {
            foreach (var item in Model.items)
            {

                var dbItem = Model.getItem(Int32.Parse(item.Key));
                <div class="row " style="display: flex;">
                    <div class="col-md-4 col-4 cart-column ">
                        <div class="row" style="padding-left:15px;">
                            <img class="cart-item-image " src="@dbItem.imageSrc" height="100%">
                            <div class="cart-item-title cart-column" style="padding-left: 15px;">@dbItem.name</div>
                        </div>
                        <p hidden>@item.Key</p>

                    </div>

                    <div class="col-md-2 col-2 cart-column ">
                        <div class="cart-price cart-column" style="padding-left: 0px;">$@dbItem.price.ToString()</div>
                    </div>

                    <div class="col-md-4 col-10 cart-quantity cart-header cart-column " >
                        <p hidden> @item.Key </p>
                        <input class="cart-quantity-input" type="number" value="@item.Value" min="0">
                        <button class="btn btn-danger" type="button" style="padding:0.8em 1em;background-color:#17a2b8;border-color:#17a2b8; ">REMOVE</button>
                    </div>
                </div>

            }
        }
    }

</section>

<div class="cart-total">
    <strong class="cart-total-title">Total</strong>
    <span class="cart-total-price">$@Model.getTotalCost()</span>

</div>

<div class="align-center">
    <button class="btn btn-primary btn-purchase" name="btn-purchase" type="button">PURCHASE</button>
</div>

<section class="mbr-section content8 cid-s2gMfRE15Z" id="content8-m"></section>

SFC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>